# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import code_generation_pb2 as code__generation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in code_generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeGenerationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamGenerate = channel.unary_stream(
                '/com.adcage.acaicodefree.CodeGenerationService/StreamGenerate',
                request_serializer=code__generation__pb2.CodeGenerationRequest.SerializeToString,
                response_deserializer=code__generation__pb2.CodeGenerationEvent.FromString,
                _registered_method=True)
        self.StreamModify = channel.unary_stream(
                '/com.adcage.acaicodefree.CodeGenerationService/StreamModify',
                request_serializer=code__generation__pb2.CodeModificationRequest.SerializeToString,
                response_deserializer=code__generation__pb2.CodeGenerationEvent.FromString,
                _registered_method=True)
        self.ValidatePrompt = channel.unary_unary(
                '/com.adcage.acaicodefree.CodeGenerationService/ValidatePrompt',
                request_serializer=code__generation__pb2.ValidatePromptRequest.SerializeToString,
                response_deserializer=code__generation__pb2.ValidatePromptResponse.FromString,
                _registered_method=True)
        self.EnhancePrompt = channel.unary_unary(
                '/com.adcage.acaicodefree.CodeGenerationService/EnhancePrompt',
                request_serializer=code__generation__pb2.EnhancePromptRequest.SerializeToString,
                response_deserializer=code__generation__pb2.EnhancePromptResponse.FromString,
                _registered_method=True)


class CodeGenerationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamModify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnhancePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerate,
                    request_deserializer=code__generation__pb2.CodeGenerationRequest.FromString,
                    response_serializer=code__generation__pb2.CodeGenerationEvent.SerializeToString,
            ),
            'StreamModify': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamModify,
                    request_deserializer=code__generation__pb2.CodeModificationRequest.FromString,
                    response_serializer=code__generation__pb2.CodeGenerationEvent.SerializeToString,
            ),
            'ValidatePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePrompt,
                    request_deserializer=code__generation__pb2.ValidatePromptRequest.FromString,
                    response_serializer=code__generation__pb2.ValidatePromptResponse.SerializeToString,
            ),
            'EnhancePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.EnhancePrompt,
                    request_deserializer=code__generation__pb2.EnhancePromptRequest.FromString,
                    response_serializer=code__generation__pb2.EnhancePromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.adcage.acaicodefree.CodeGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.adcage.acaicodefree.CodeGenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeGenerationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.adcage.acaicodefree.CodeGenerationService/StreamGenerate',
            code__generation__pb2.CodeGenerationRequest.SerializeToString,
            code__generation__pb2.CodeGenerationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamModify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.adcage.acaicodefree.CodeGenerationService/StreamModify',
            code__generation__pb2.CodeModificationRequest.SerializeToString,
            code__generation__pb2.CodeGenerationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.CodeGenerationService/ValidatePrompt',
            code__generation__pb2.ValidatePromptRequest.SerializeToString,
            code__generation__pb2.ValidatePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnhancePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.adcage.acaicodefree.CodeGenerationService/EnhancePrompt',
            code__generation__pb2.EnhancePromptRequest.SerializeToString,
            code__generation__pb2.EnhancePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
