# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x17\x63om.adcage.acaicodefree\"0\n\x0e\x41iResponseData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08\x66\x61llback\x18\x02 \x01(\x08\">\n\x0fToolRequestData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\"O\n\x10ToolExecutedData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\t\"*\n\tErrorData\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x1b\n\x08\x44oneData\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nStatusData\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x8e\x01\n\x0e\x41ttachmentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x14\n\x0cstorage_type\x18\x05 \x01(\t\x12\x14\n\x0cstorage_path\x18\x06 \x01(\t\x12\x0b\n\x03url\x18\x07 \x01(\t*^\n\x0b\x43odeGenType\x12\x1d\n\x19\x43ODE_GEN_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0bSINGLE_FILE\x10\x01\x12\x0e\n\nMULTI_FILE\x10\x02\x12\x0f\n\x0bVUE_PROJECT\x10\x03*W\n\x0eGenerationMode\x12\x1f\n\x1bGENERATION_MODE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41PPLICATION\x10\x01\x12\x13\n\x0fTEST_PLAYGROUND\x10\x02*\x8f\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x41GENT_START\x10\x01\x12\x0f\n\x0b\x41I_RESPONSE\x10\x02\x12\x10\n\x0cTOOL_REQUEST\x10\x03\x12\x11\n\rTOOL_EXECUTED\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x12\x08\n\x04\x44ONE\x10\x06\x12\n\n\x06STATUS\x10\x07\x42\'\n#com.adcage.acaicodefree.grpc.commonP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.adcage.acaicodefree.grpc.commonP\001'
  _globals['_CODEGENTYPE']._serialized_start=485
  _globals['_CODEGENTYPE']._serialized_end=579
  _globals['_GENERATIONMODE']._serialized_start=581
  _globals['_GENERATIONMODE']._serialized_end=668
  _globals['_EVENTTYPE']._serialized_start=671
  _globals['_EVENTTYPE']._serialized_end=814
  _globals['_AIRESPONSEDATA']._serialized_start=41
  _globals['_AIRESPONSEDATA']._serialized_end=89
  _globals['_TOOLREQUESTDATA']._serialized_start=91
  _globals['_TOOLREQUESTDATA']._serialized_end=153
  _globals['_TOOLEXECUTEDDATA']._serialized_start=155
  _globals['_TOOLEXECUTEDDATA']._serialized_end=234
  _globals['_ERRORDATA']._serialized_start=236
  _globals['_ERRORDATA']._serialized_end=278
  _globals['_DONEDATA']._serialized_start=280
  _globals['_DONEDATA']._serialized_end=307
  _globals['_STATUSDATA']._serialized_start=309
  _globals['_STATUSDATA']._serialized_end=338
  _globals['_ATTACHMENTINFO']._serialized_start=341
  _globals['_ATTACHMENTINFO']._serialized_end=483
# @@protoc_insertion_point(module_scope)
