# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import knowledge_service_pb2 as knowledge__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeServiceStub:
    """============================================================
    知识库管理服务（Java → Python）
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListLibraries = channel.unary_unary(
                '/protoflow.knowledge.KnowledgeService/ListLibraries',
                request_serializer=knowledge__service__pb2.ListLibrariesRequest.SerializeToString,
                response_deserializer=knowledge__service__pb2.ListLibrariesResponse.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/protoflow.knowledge.KnowledgeService/SearchKnowledge',
                request_serializer=knowledge__service__pb2.SearchKnowledgeRequest.SerializeToString,
                response_deserializer=knowledge__service__pb2.SearchKnowledgeResponse.FromString,
                _registered_method=True)
        self.TriggerReindex = channel.unary_unary(
                '/protoflow.knowledge.KnowledgeService/TriggerReindex',
                request_serializer=knowledge__service__pb2.TriggerReindexRequest.SerializeToString,
                response_deserializer=knowledge__service__pb2.TriggerReindexResponse.FromString,
                _registered_method=True)
        self.GetRagStatus = channel.unary_unary(
                '/protoflow.knowledge.KnowledgeService/GetRagStatus',
                request_serializer=knowledge__service__pb2.GetRagStatusRequest.SerializeToString,
                response_deserializer=knowledge__service__pb2.GetRagStatusResponse.FromString,
                _registered_method=True)


class KnowledgeServiceServicer:
    """============================================================
    知识库管理服务（Java → Python）
    ============================================================

    """

    def ListLibraries(self, request, context):
        """查询所有文档库列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """语义检索知识库
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerReindex(self, request, context):
        """触发重新索引（前端上传文档后调用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagStatus(self, request, context):
        """获取 RAG 系统状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListLibraries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLibraries,
                    request_deserializer=knowledge__service__pb2.ListLibrariesRequest.FromString,
                    response_serializer=knowledge__service__pb2.ListLibrariesResponse.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=knowledge__service__pb2.SearchKnowledgeRequest.FromString,
                    response_serializer=knowledge__service__pb2.SearchKnowledgeResponse.SerializeToString,
            ),
            'TriggerReindex': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerReindex,
                    request_deserializer=knowledge__service__pb2.TriggerReindexRequest.FromString,
                    response_serializer=knowledge__service__pb2.TriggerReindexResponse.SerializeToString,
            ),
            'GetRagStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagStatus,
                    request_deserializer=knowledge__service__pb2.GetRagStatusRequest.FromString,
                    response_serializer=knowledge__service__pb2.GetRagStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoflow.knowledge.KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protoflow.knowledge.KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService:
    """============================================================
    知识库管理服务（Java → Python）
    ============================================================

    """

    @staticmethod
    def ListLibraries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoflow.knowledge.KnowledgeService/ListLibraries',
            knowledge__service__pb2.ListLibrariesRequest.SerializeToString,
            knowledge__service__pb2.ListLibrariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoflow.knowledge.KnowledgeService/SearchKnowledge',
            knowledge__service__pb2.SearchKnowledgeRequest.SerializeToString,
            knowledge__service__pb2.SearchKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerReindex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoflow.knowledge.KnowledgeService/TriggerReindex',
            knowledge__service__pb2.TriggerReindexRequest.SerializeToString,
            knowledge__service__pb2.TriggerReindexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protoflow.knowledge.KnowledgeService/GetRagStatus',
            knowledge__service__pb2.GetRagStatusRequest.SerializeToString,
            knowledge__service__pb2.GetRagStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
